### PR TITLE
Bazel icon Support for .BAZEL and WORKSPACE icons

### LINKED ISSUE #137: Icon missing for BUILD.bazel
BAZEL Icon is missing for BUILD.bazel and WORKSPACE but available for `.bazelrc` and `.bzl`
image

If possible I would like to work on this

### PR DESCRIPTION
**Pull request by FareesHussain**
Fixes #137

### CODE REVIEW

**Comment by FareesHussain** [comment]
@EnixCoda can you review this.

**Comment by EnixCoda** [comment]
May not merge the change as it is updating a generated file. Please read my comments in #137

**Comment by FareesHussain** [comment]
> May not merge the change as it is updating a generated file. Please read my comments in #137 

As it is a generated file shouldn't we add it in the `.gitignore`. 
Let me know If I'm wrong

**Comment by EnixCoda** [comment]
It is generally the best practice to do that. But the generating progress is not fully automated as I can recall. I'll give one more try when generating it next time to make it fully automated so that it can be added to `.gitignore`.

**Pull request closed without merging**
