### PR TITLE
Add themes to gitako sidebar

### PR DESCRIPTION
**Pull request by benavern**
Hi!

I'm very interested in a dark theme for Gitako that i've been using for only 3 days.

I've seen that you already advised in https://github.com/EnixCoda/Gitako/issues/29 to use some third party extensions to provide styling. I however think that users would benefit a real theming feature in your extension.

Then, here is a proposal for a simple themes chooser in which I created a dark theme (I already use it with an unpacked version of the extension...)

image

image

Would it be interesting for you ?

### CODE REVIEW

**Comment by EnixCoda** [comment]
Looks cool! Thank you @benavern 

As you may have noticed, Gitako in your screenshots is different from the latest release. That's because `master` branch is way behind `develop`. Please change this PR's base to `develop` and resolve conflicts.

When you are updating your code after changing base, please consider applying these changes as well:

1. As [primer](https://primer.style/) is available on develop branch, please apply colors from [color system](https://primer.style/css/support/color-system) and [color variables](https://primer.style/css/support/variables). The colors you picked do look good! I just want to make sure all colors in Gitako are picked from single color system.
1. Use [mixin](https://sass-lang.com/documentation/at-rules/mixin) to simplify dark theme stylesheets.
    in `src/theme-dark.sass`
    ```sass
    @mixin theme-dark {
      // styles for dark theme
    }
    ```

    in `src/content.sass`
    ```sass
    @import './theme-dark.sass'

    .@{name}-side-bar {
      &.theme-dark {
        @include theme-dark
      }
    }
    ```

Thanks for your contribution!

**Comment by benavern** [comment]
Oh! I didn't notice :(

You should add a little section to your readme so that we know how to contribute. ;-)

I'm gonna try to update the pull request with the develop branch and update that pull request then...

**Comment by benavern** [comment]
Hi, here is what I did:
1. `git reset --soft HEAD~1`
1. `git stash`
1. `git rebase develop`
1. `git stash pop` and fixed my conflicts
1. made the changes you advised me to do
1. `git push --force`

Why is there those 7 README changes ?

**Comment by EnixCoda** [comment]
I could have deprecated `master` branch to prevent that, sorry :P

You act so quick! And I do appreciate it that you took my suggestions. I'll review code when I have time. Thanks!

Few git tips may help you:

- You could have replaced `3.` with `git checkout develop` to get rid of the readme changes. As the readme commits happened on `master` directly, when rebasing `develop`, all commits not found in `develop` will be added to it!
- Git cherry pick may help you solving such git conflicts easier:
    1. git checkout -b feature/dark-theme develop
    1. git cherry-pick feature/themes (this applies the top commit of `feature/themes`)
    1. ...resolve conflicts
    1. git commit
    1. git push --force

**Comment by benavern** [comment]
yes, but I did this assuming you were using gitflow, rebasing would not have been an issue. 

I'll try a new `git push --force` without those commits, I'm just not very proud of the "force" flag on each push ^^

If you don't mind, I maybe have 1 or 2 ideas to make the whole extension "themable" (not only the sidebar but the little icon and stuff that are added to the DOM...). That doesn't involve a lot of changes so, maybe i'll take time for that before the end of the weekend and add commits here again ;)

By the way I'm from France (it maybe explains why you think i'm quick because of the jet lag?)

**Comment by EnixCoda** [comment]
I see, good to see those commits are gone now!

Expanding the theming feature sounds very good! Especially making the toggle button themable (including the little icon you mentioned).

As for the stuff added to DOM, I am not sure if we should theme them. I've made them look as natural to Github as possible, as if they were native GitHub features. Would theming them break that?

**Comment by benavern** [comment]
I just touched to everything related to the extension, not the rest.

I'm not sure of what i did on the last commit (I don't know react that much, but it works)

Here are some screenshots :

(Note that i'm using the [github dark theme](https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp) extension and it goes very well together no ? :-) )

Capture d’écran 2020-04-24 à 13 20 05
Capture d’écran 2020-04-24 à 13 21 42
Capture d’écran 2020-04-24 à 13 21 35
Capture d’écran 2020-04-24 à 13 20 35
Capture d’écran 2020-04-24 à 13 20 19

**Comment by EnixCoda** [comment]
Wow, that looks really good! Good work!

May I slightly modify your code to fix minor issues directly and then merge?

**Comment by benavern** [comment]
Yes sure!
Can't wait to create an other theme :)

**Comment by EnixCoda** [comment]
I have another idea for dark theme, with much less stylesheets, and its result is beyond my expectation. Let's take a look at the result first:

image

image

One line code to achieve that:
```scss
.gitako-position-wrapper.dark-theme {
  filter: invert(100%);
}
```

To prevent icons' color being inverted, add this:
```scss
.gitako-position-wrapper.dark-theme .node-item-icon {
  filter: invert(100%);
}
```

Drawback: this does not work well with dark reader when dark mode is activated.

PS: I'm not saying I'll abandon your work. The amount of CSS variables is somehow going of out my control, I find it hard to maintain as I found few small style issues caused by them, tried to resolve then failed. I'll give another try later.

**Comment by EnixCoda** [comment]
Pushed few changes related to react usages.

**Comment by benavern** [comment]
Thank you, I like the fact that now it is much more clear how it works to change theme.

I know that trick but don't really like it (personal opinion) but what is great is that it could simply be a new theme! 

for example, call it "inverted" and just at the end of the content file, after the dark theme:

 ```css
// inverted theme keeps default colors and inverts it
.#{$name}-theme-inverted {
    .gitako-position-wrapper {
      filter: invert(100%);

      .node-item-icon {
        filter: invert(100%);
      }
    }
}
```

I think css variables are a very good thing for theming, you just have to decide how much you want to keep, for me it is a pretty reasonable number here, that could be usefull for other theme colors :)

**Comment by EnixCoda** [comment]
Yes, naming it inverted mode instead of dark mode is more accurate :P

**Comment by benavern** [comment]
Here are 2 more themes:
## inverted


## material


What do you think? Do you now see why I think css variables are great for this project and how this is the right number of them that we have ?

**Comment by benavern** [comment]
> I find it hard to maintain as I found few small style issues caused by them, tried to resolve then failed. I'll give another try later.

Could I help with it ?

**Comment by EnixCoda** [comment]
I recalled the reason push me to implement Gitako and thought this feature over again. Gitako was designed to provide features that help improving UX on GitHub and no more than that. **Be simple and useful**. It is hard to make a clear definition of that. At least I expect it to work like a part of GitHub.

In my opinion, adding more themes does not help with that or even might break that (look too attractive). Providing too many options to users is also not what I'd do. I do like your dark theme, because GitHub's header is dark.

And I'm not sure how many users would really need or like this feature. Can we suspend this PR and wait for more requests on it?

**Comment by benavern** [comment]
I understand what you mean and I have to say that I maybe pushed too much on my idea to create more themes. 

You can suspend the PR or just keep the dark theme and merge.

Personally, I will keep going with the unpacked version as long as the dark theme won't be available in the official version because of the fact that I use GitHub everyday with the dark theme extension, which makes my eyes not hurt when going from my editor to the website.

Thank you for the support on this PR anyway and good luck for the future :-)

**Comment by EnixCoda** [comment]
Thank you!

> because of the fact that I use GitHub everyday with the dark theme extension, which makes my eyes not hurt when going from my editor to the website.

This makes me confused. If you are using dark theme extensions, e.g. stylus or dark reader, they should be able to furnish Gitako into dark theme quite well. Why would you need Gitako to provide dark theme?

**Comment by benavern** [comment]
The dark theme extension (https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp) is just providing dark theme to the github website. Gitako is added on top of the website and is not themed well with this extension. I thought that adding the dark theme directly in gitako would have been a good solution because, as you said, it feats well with the black header of the website and for those who are customizing it via stylish for example.

However, I understand very well what you said here: 
> Gitako was designed to provide features that help improving UX on GitHub and no more than that. Be simple and useful. It is hard to make a clear definition of that. As least I expect it to work like a part of GitHub.

I respect that and won't push more for that PR. I'll continue using my unpacked version anyway because I prefer the dark theme on it. 

Maybe one day I'll create an extension with just the dark theme for gitako, or a stylesheet on stylish, but for now, that works ok for me :) (And if I'm brave einough I'll be able to rebase any change you make in the develop branch and have any new feature you make in preview 👍 )

Thank you for the extension, it is great ( even in light colors XD )

**Comment by EnixCoda** [comment]
You don't have to create a stylesheet on stylish as it has been done. And that is exactly what I mean in #29 

See https://github.com/StylishThemes/GitHub-Dark#supported-github-extensions

**Comment by benavern** [comment]
Yeah I understood, but then I'll have to have all the website themed with that theme that I don't like as much as the one I currently use. Thats a better approach for your concern where you want gitako to look part of github. I just didn't have that in mind at the time and came out with a different approach. That does not feat your point of view and I totaly respect that :) No worries ;)

**Comment by benavern** [comment]
An other solution would be that I make a pull request to the theme I use and add styles for the gitako plugin (same way https://github.com/StylishThemes/GitHub-Dark#supported-github-extensions did)

**Comment by EnixCoda** [comment]
Good luck!

**Pull request closed without merging**
