### PR TITLE
feat: add bookmark

### PR DESCRIPTION
**Pull request by bxb100**
it shouldn't merge to upstream currently

## feat

* support bookmark
* update to MV3 

image

## todo

- [ ] fix broken `webext-domain-permission-toggle`
- [ ] add search filter
- [ ] support other webiste

## test 

- [x] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by EnixCoda** [comment]
Hi @bxb100  Thanks for drafting this feature and implement the PR. I can see you have put a lot of effort into this! Really appreciate it!

Before you move on further, would you mind sharing some thoughts of it? Actually I have some questions and suggestions for it.

Questions
1. Why would this bookmark feature be useful?
1. When compared to browser bookmark, or GitHub star feature, was it still more useful?

Suggestions
1. Extract this PR into 2 different ones, for MV3 and the feature, then submit them individually.
2. Actually I have been working on MV3 as well. And I did not made it because some feature support was lost :( MV3 is not as cool as I expected

:)

**Comment by bxb100** [comment]
Hi, @EnixCoda , this PR just shared my thoughts and meets my own needs, it is not prepared for merging.

**Comment by bxb100** [comment]
If this is bothering you, I will close this PR

**Comment by EnixCoda** [comment]
No problem :) I thought it was expected to be merged someday because it was described it as `currently` in the beginning.

If that was not your plan, you may close the PR in this source repo and open PRs in your forked repo, e.g. merge `bxb100:feature/bookmark` -> `bxb100:develop` (instead of `EnixCoda:develop`)

Feature request and discussion are always welcome via GitHub issue and discussion in this repo :)

**Comment by bxb100** [comment]
=. = I knew, that just because the GitHub heatmap did not count that behavior

**Pull request closed without merging**
