### PR TITLE
feat: click icon open raw content

### PR DESCRIPTION
**Pull request by cipchk**

### CODE REVIEW

**Comment by EnixCoda** [comment]
Hi @cipchk 

Thank you for contributing this PR!

Besides the code changes, there are few concerns from me:
1. Users should be aware of what would happen if click on the icon. `Clicking on the icon` does not make a strong connection to `opening as raw content` for me, not that intuitive.
1. What are the situations that users opening files in raw **before** navigating to the file's page? If navigate first instead, the `Raw` button provided on the page should be a better choice.

**Comment by cipchk** [comment]
It is really difficult to distinguish at present, I can modify the following effects:

help

Abort the feature. the simple reason is that I often need to use it to quickly open the original :).

**Comment by EnixCoda** [comment]
Such an effect on hover will be a good hint.

You can keep this PR open to get more thumb ups so we can push this further then.

**Comment by cipchk** [comment]
@EnixCoda 抱歉，我不是很懂 React，因此不确定 `const hover = useStates(false)` 这种方式的写法是否正确，并且是否存在性能的问题。

**Comment by EnixCoda** [comment]
问题不大

换做我的话，可能会选择使用 css `:hover` 实现

**Comment by kidonng** [comment]
This is one of the remaining features I miss from Octotree. Is there anything blocking this PR?

**Comment by EnixCoda** [comment]
@kidonng For features that I personally do not need, I'd see enough users upvoting for it before merging.

**Comment by cipchk** [comment]
@kidonng Try to press <kbd>.</kbd> will be surprises, I'm used to it.

github dev

**Comment by kidonng** [comment]
> For features that I personally do not need, I'd see enough users upvoting for it before merging.

Fair enough, but this is a (relatively) simple feature unlocking endless possibilities:

- You can Alt + click the raw link to download the file, addressing #72
- Alternatively, You can quickly copy the raw link and pass it to `curl` or any other utility
- You can quick view the original content of a text file (for copying, etc.), original size of an image (without the overhead introduced by GitHub's rendering process)
- Paired with other extensions (such as [maxurl](https://github.com/qsniyg/maxurl)) you can have image preview when hovering the link, etc.

There's just too much you can do with the raw link. I'm sure you will find it useful as well.

> Try to press . will be surprises, I'm used to it.

I know this but it's a completely different thing.

**Comment by EnixCoda** [comment]
@kidonng  Thanks, I can see all these benefits, if it is in users' workflow. But none of them are in mine, that is why I am hesitant.

**Pull request closed without merging**
